id: P9090EE0A
initial_creation_type: input
source_metadata:
  title: Abhisamayālaṃkāra Series
  language: es
  description: 'Texts related to the Abhisamayālaṃkāra (mngon rtogs rgyan) or Clear
    Ornament of Realization, one of the Five Treatises of Maitreyanātha:'
  volume:
    92c7a7d96f0f4c69a3efaf9406eb4e54:
      title: 'Words from the Lineage Masters to Clarify Maitreyanātha''s Vision: An
        Overview of the Perfection of Wisdom''s Ornament of Realization'
      parent: Commentaries
    e15d5df76e044cfd80cf57913f652129:
      title: Prologue to Abhisamayālaṃkāra Commentary
      parent: Commentaries
    02814ad825a4450aba31741948660089:
      title: A Preliminary to the Explanation of the Prajñāpāramitā
      parent: Commentaries
    a301443c5ce8439d9336343c6f17b6b8:
      title: 'The Words of Jigme Chökyi Wangpo: A Commentary Presenting the Subject
        Matter of the Great Treatise Abhisamayālaṃkāra'
      parent: Commentaries
    2f3a25ed25fd43858f4e160c6368dea5:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Commentaries
    2ad1f6b9b57e401c914884843d2c344f:
      title: The Eightfold Nature of Profundity from the Abhisamayālaṃkāra
      parent: Notes
created_at: '2022-03-01T02:29:29.032585'
last_modified_at: '2022-03-01T02:29:29.032590'
